### ISSUE TITLE
[ng-core] Error: _this.subscribeTo is not a function

### ISSUE THREAD

**Issue by fynnfeldpausch** [simontonsoftware/s-libs#45]
Using the `WrappedFormControlSuperclass` results in an error for me as the `subscribeTo` function is not defined. It seems that this functionality is coming from the _rxjs_ library and is not mixed into the class. Am I missing something?

https://stackblitz.com/edit/angular-xbvuer?file=src/app/control.component.ts

**Comment by ersimont** [comment]
Thank you for filing the issue! This is interesting. Can you replicate in a regular `ng serve` situation, or only in stackblitz? I'm wondering if it has to do with the `umd` bundles in particular.

**Comment by fynnfeldpausch** [comment]
I am not able to replicate it locally. I was actually trying to replicate / file another bug that I came across and then got stuck trying to build a stackblitz for it :-D

**Comment by ersimont** [comment]
😀😞

This issue with the UMD bundles on stackblitz just looks strange. The error is that `_subscribeTo` is not a function (with the leading underscore). Looking through the UMD bundles that are generated with version 12, that string is never found.

So I upgraded things in the stackblitz to Angular 12, and came up with a very similar, but different error: `_this.setUpOuterToInner$ is not a function`.

My best guess so far is that something is not transpiling to ES5 properly when the CLI creates those UMD bundles (e.g. the newer [mixin pattern](https://www.typescriptlang.org/docs/handbook/mixins.html)). I can investigate this more, but it sounds like it's not actually a problem for you. Please feel free to open a separate issue for whatever your real problem is! Maybe reproduce it locally and make a little git repo?

**Comment by ersimont** [comment]
The best guess about this issue was that it had to do with UMD bundles. Those are no longer published with the cli. Closing this issue assuming it is no longer reproducible in recent versions.
